[package]
name = "passworth"
version = "0.1.0"
edition = "2021"

[features]
native = ["dep:aargvark"]

[dependencies]
glove = { version = "0.4" }
zbase32 = "0.1"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aargvark = { version = "0.7", optional = true }
